import { useEffect, useMemo, useState } from "react";
import Badge from "../components/common/Badge";
import StatCard from "../components/common/StatCard";
import { formatSourceLabel } from "../utils/display";
import "../styles/reports-v32.css";

function normalizeReportType(type = "") {
  const value = String(type || "report").toLowerCase();
  if (value.includes("camera") || value.includes("tamper") || value.includes("integrity")) return "Camera Integrity";
  if (value.includes("incident")) return "Incident";
  if (value.includes("anomaly")) return "Anomaly";
  return "General";
}

function reportKindClass(type = "") {
  return normalizeReportType(type).toLowerCase().replaceAll(" ", "-");
}

function formatBytes(bytes) {
  const value = Number(bytes || 0);
  if (!Number.isFinite(value) || value <= 0) return "0 B";
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
  return `${(value / (1024 * 1024)).toFixed(1)} MB`;
}

function friendlyReportName(filename = "") {
  const raw = String(filename || "Report").replace(/\.txt$/i, "");
  if (raw.includes("camera_health_report")) return raw.replace("camera_health_report_", "Camera Integrity #");
  if (raw.includes("incident_report")) return raw.replace("incident_report_", "Incident #");
  if (raw.includes("anomaly_report")) return raw.replace("anomaly_report_", "Anomaly #");
  return raw.replace(/_/g, " ");
}

function compactFilename(filename = "", max = 58) {
  const raw = String(filename || "Report");
  if (raw.length <= max) return raw;
  const front = Math.floor(max * 0.58);
  const back = Math.floor(max * 0.34);
  return `${raw.slice(0, front)}…${raw.slice(-back)}`;
}

function safeValue(value, fallback = "—") {
  const text = String(value ?? "").trim();
  return text && text !== "—" ? text : fallback;
}

function formatSourceForReport(value = "") {
  const clean = String(value || "").trim();
  if (!clean || clean === "—") return "—";
  return formatSourceLabel(clean);
}

function extractField(content = "", label) {
  const lines = String(content || "").split(/\r?\n/);
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const direct = new RegExp(`^\\s*${escaped}\\s*:\\s*(.*)$`, "i");

  for (let index = 0; index < lines.length; index += 1) {
    const match = lines[index].match(direct);
    if (!match) continue;

    const sameLine = match[1]?.trim();
    if (sameLine) return sameLine;

    const collected = [];
    for (let next = index + 1; next < lines.length; next += 1) {
      const value = lines[next].trim();
      if (!value) {
        if (collected.length) break;
        continue;
      }
      if (/^[A-Za-z][A-Za-z /_-]{2,}:/.test(value)) break;
      if (/^Generated By\s*:/i.test(value)) break;
      collected.push(value);
      if (collected.join(" ").length > 180) break;
    }

    return collected.join(" ").trim() || "—";
  }

  return "—";
}

function parseReportContent(content = "") {
  const reportType = extractField(content, "Report Type");
  const anomalyScore = extractField(content, "Anomaly Score");
  const severity = extractField(content, "Severity");
  const density = extractField(content, "Density Level");
  const dangerZone = extractField(content, "Danger Zone");
  const anomalyZone = extractField(content, "Anomaly Zone");
  const generatedAt = extractField(content, "Generated At");
  const cameraProfile = extractField(content, "Camera Profile");
  const tamperType = extractField(content, "Tamper Type");

  return {
    reportType,
    generatedAt,
    cameraProfile: formatSourceForReport(cameraProfile),
    totalPeople: extractField(content, "Total People"),
    zoneCount: extractField(content, "Zone Count"),
    occupancy: extractField(content, "Occupancy"),
    density,
    dangerZone,
    duration: extractField(content, "Incident Duration"),
    anomalyType: extractField(content, "Anomaly Type"),
    anomalyScore,
    severity,
    tamperType,
    primaryZone: dangerZone !== "—" ? dangerZone : anomalyZone,
    severityScore: severity !== "—" ? severity : anomalyScore,
    action: extractField(content, "Recommended Action"),
    isLoading: String(content || "").toLowerCase().includes("loading report"),
  };
}

function ReportMetric({ label, value }) {
  return (
    <div className="report-console-metric">
      <span>{label}</span>
      <strong>{safeValue(value)}</strong>
    </div>
  );
}

function ReportTypeBadge({ type }) {
  const normalized = normalizeReportType(type);
  return <Badge value={normalized} type={reportKindClass(normalized)} />;
}

function ReportRecord({ report, selected, onPreview }) {
  const type = normalizeReportType(report.type);

  return (
    <article className={`report-console-record ${reportKindClass(type)} ${selected ? "selected" : ""}`}>
      <button
        type="button"
        className="report-console-record-main"
        onClick={() => onPreview(report)}
        title={report.filename}
      >
        <span className="report-console-record-top">
          <ReportTypeBadge type={type} />
          <small>{formatBytes(report.size)}</small>
        </span>
        <strong>{friendlyReportName(report.filename)}</strong>
        <em>{report.created || "Unknown date"}</em>
      </button>

      <div className="report-console-record-actions">
        <button type="button" onClick={() => onPreview(report)}>Inspect</button>
        {report.url && <a href={report.url} target="_blank" rel="noreferrer">TXT</a>}
        {report.pdf_url && <a href={report.pdf_url} target="_blank" rel="noreferrer" className="pdf-link">PDF</a>}
      </div>
    </article>
  );
}

export default function ReportsPage({ data }) {
  const {
    reports = [],
    selectedReportContent,
    openReport,
    fetchDashboardData,
  } = data;

  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All");
  const [previewFilename, setPreviewFilename] = useState("");
  const [isOpening, setIsOpening] = useState(false);

  const sortedReports = useMemo(
    () => [...reports].sort((a, b) => String(b.created || "").localeCompare(String(a.created || ""))),
    [reports]
  );

  const reportStats = useMemo(() => {
    const incidents = sortedReports.filter((report) => normalizeReportType(report.type) === "Incident").length;
    const anomalies = sortedReports.filter((report) => normalizeReportType(report.type) === "Anomaly").length;
    const cameraIntegrity = sortedReports.filter((report) => normalizeReportType(report.type) === "Camera Integrity").length;

    return {
      total: sortedReports.length,
      incidents,
      anomalies,
      cameraIntegrity,
      latest: sortedReports[0]?.created || "No report yet",
    };
  }, [sortedReports]);

  useEffect(() => {
    if (!sortedReports.length) return;
    if (previewFilename && sortedReports.some((report) => report.filename === previewFilename)) return;
    const firstReport = sortedReports[0];
    setPreviewFilename(firstReport.filename);
    openReport(firstReport.filename);
  }, [sortedReports, previewFilename, openReport]);

  const filteredReports = useMemo(() => {
    const search = query.trim().toLowerCase();

    return sortedReports.filter((report) => {
      const type = normalizeReportType(report.type);
      const matchesFilter = filter === "All" || type === filter;
      const matchesSearch = !search || [report.filename, report.created, report.type]
        .filter(Boolean)
        .some((value) => String(value).toLowerCase().includes(search));
      return matchesFilter && matchesSearch;
    });
  }, [sortedReports, filter, query]);

  const activeReport = useMemo(
    () => sortedReports.find((report) => report.filename === previewFilename) || null,
    [sortedReports, previewFilename]
  );

  const activeDetails = useMemo(
    () => parseReportContent(selectedReportContent),
    [selectedReportContent]
  );

  async function handlePreview(report) {
    setPreviewFilename(report.filename);
    setIsOpening(true);
    try {
      await openReport(report.filename);
    } finally {
      setIsOpening(false);
    }
  }

  function clearSearch() {
    setQuery("");
    setFilter("All");
  }

  const hasReports = sortedReports.length > 0;
  const selectedType = normalizeReportType(activeReport?.type);
  const readableSource = safeValue(activeDetails.cameraProfile, "CrowdVision");
  const loading = isOpening || activeDetails.isLoading;

  return (
    <>
      <section className="page-title-panel report-command-hero">
        <p className="section-kicker">Investigation Command</p>
        <h1>Report Intelligence Center</h1>
        <p>
          Review incident, anomaly, and camera-integrity evidence in one investigation desk.
          The report registry remains visible while the selected record opens beside it.
        </p>
      </section>

      <section className="cards-grid report-metrics-row report-console-stats">
        <StatCard label="Total Reports" value={reportStats.total} />
        <StatCard label="Incident Records" value={reportStats.incidents} variant="warning" />
        <StatCard label="Anomaly Records" value={reportStats.anomalies} variant="danger" />
        <StatCard label="Camera Integrity" value={reportStats.cameraIntegrity} variant="cyan" />
      </section>

      <section className="panel report-console-shell">
        <div className="report-console-heading">
          <div>
            <p className="section-kicker">Evidence Desk</p>
            <h2>Investigation Registry</h2>
            <span>Search, inspect, preview, and export generated CrowdVision evidence records.</span>
            <small className="v44-report-latest">Latest generated: {reportStats.latest}</small>
          </div>
          <button type="button" className="report-console-refresh" onClick={fetchDashboardData}>Refresh Reports</button>
        </div>

        <div className="report-console-toolbar">
          <label className="report-console-search">
            <span>Search reports</span>
            <input
              type="search"
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Search filename, type, or date..."
            />
          </label>

          <div className="report-console-filters" aria-label="Report type filter">
            {[
              ["All", reportStats.total],
              ["Incident", reportStats.incidents],
              ["Anomaly", reportStats.anomalies],
              ["Camera Integrity", reportStats.cameraIntegrity],
            ].map(([item, count]) => (
              <button
                key={item}
                type="button"
                className={filter === item ? "active" : ""}
                onClick={() => setFilter(item)}
              >
                {item} <strong>{count}</strong>
              </button>
            ))}
          </div>
        </div>

        {!hasReports ? (
          <div className="report-console-empty">
            <strong>No reports yet.</strong>
            <span>Start monitoring. CrowdVision will create reports when safety events or camera-integrity issues are recorded.</span>
          </div>
        ) : (
          <div className="report-console-workbench">
            <section className="report-console-registry" aria-label="Report registry">
              <div className="report-console-list-head">
                <div>
                  <span>Report queue</span>
                  <strong>{filteredReports.length} visible records</strong>
                </div>
                {(query || filter !== "All") && <button type="button" onClick={clearSearch}>Clear</button>}
              </div>

              {filteredReports.length === 0 ? (
                <div className="report-console-empty small">
                  <strong>No match found.</strong>
                  <span>Clear your search or change the filter.</span>
                </div>
              ) : (
                <div className="report-console-list" aria-label="Generated reports">
                  {filteredReports.slice(0, 250).map((report, index) => (
                    <ReportRecord
                      key={`${report.filename}-${index}`}
                      report={report}
                      selected={activeReport?.filename === report.filename}
                      onPreview={handlePreview}
                    />
                  ))}
                </div>
              )}
            </section>

            <aside className="report-console-preview" aria-live="polite">
              {!activeReport ? (
                <div className="report-console-preview-empty">
                  <p className="section-kicker">Official Preview</p>
                  <h2>Select a report</h2>
                  <span>Choose any record from the registry to inspect it here.</span>
                </div>
              ) : (
                <>
                  <div className="report-console-preview-top">
                    <div>
                      <p className="section-kicker">Official Preview</p>
                      <h2>{friendlyReportName(activeReport.filename)}</h2>
                      <span>{compactFilename(activeReport.filename)}</span>
                    </div>
                    <ReportTypeBadge type={selectedType} />
                  </div>

                  <div className="report-console-dossier">
                    <div className="report-console-status-card">
                      <span>Report Status</span>
                      <strong>{loading ? "Loading Evidence" : "Evidence Ready"}</strong>
                    </div>

                    <ReportMetric label="Type" value={safeValue(activeDetails.reportType, selectedType)} />
                    <ReportMetric label="Generated" value={safeValue(activeDetails.generatedAt, activeReport.created)} />
                    <ReportMetric label="Source" value={readableSource} />
                    <ReportMetric label="People" value={activeDetails.totalPeople} />
                    <ReportMetric label="Occupancy" value={activeDetails.occupancy} />
                    <ReportMetric label="Density" value={activeDetails.density} />
                    <ReportMetric label="Zone" value={activeDetails.primaryZone} />
                    <ReportMetric
                      label={selectedType === "Camera Integrity" ? "Integrity Issue" : "Severity / Score"}
                      value={selectedType === "Camera Integrity" ? activeDetails.tamperType : activeDetails.severityScore}
                    />
                  </div>

                  <div className="report-console-action-card">
                    <span>Recommended Action</span>
                    <strong>{safeValue(activeDetails.action, "Review the full evidence record and confirm operational response.")}</strong>
                  </div>

                  <div className="report-console-downloads">
                    {activeReport.url && <a href={activeReport.url} target="_blank" rel="noreferrer">Download TXT</a>}
                    {activeReport.pdf_url && <a href={activeReport.pdf_url} target="_blank" rel="noreferrer" className="pdf-link">Download PDF</a>}
                  </div>

                  <article className="report-console-document">
                    <div className="report-console-document-head">
                      <span>Raw Evidence Record</span>
                      <strong>{formatBytes(activeReport.size)}</strong>
                    </div>
                    <pre>{selectedReportContent || "Loading report..."}</pre>
                  </article>
                </>
              )}
            </aside>
          </div>
        )}
      </section>
    </>
  );
}